# Generated by Django 4.2.5 on 2023-09-18 13:44

import app.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('audio', models.FileField(max_length=500, upload_to=app.models.get_episode_audio_path)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'episode',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(null=True)),
                ('slug', models.SlugField()),
                ('description', models.TextField(null=True)),
                ('attachment', models.FileField(upload_to=app.models.get_podcast_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'podcast',
            },
        ),
        migrations.CreateModel(
            name='UpVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.episode')),
            ],
            options={
                'db_table': 'upvotes',
            },
        ),
    ]
